export const bookClubQuotes: string[] = [
  // Real quotes from famous people/authors
  'a reader lives a thousand lives before he dies. — George R.R. Martin',
  'so many books, so little time. — Frank Zappa',
  'reading is dreaming with open eyes. — Anonymous proverb',
  'there is no friend as loyal as a book. — Ernest Hemingway',
  'a room without books is like a body without a soul. — Cicero',
  'books are a uniquely portable magic. — Stephen King',
  'the reading of all good books is like conversation with the finest minds of past centuries. — René Descartes',
  'Paradise will be a kind of library. — Jorge Luis Borges',
  'books let you travel without moving your feet. — Jhumpa Lahiri',
  'once you learn to read, you will be forever free. — Frederick Douglass',
  'you can never get a cup of tea large enough or a book long enough to suit me. — C.S. Lewis',
  'books are the plane, the train, and the road — they are the destination and the journey. — Anna Quindlen',
  'until I feared I would lose it, I never loved to read. — Harper Lee',
  "there is more treasure in books than in all the pirate's loot on Treasure Island. — Walt Disney",
  'a book is a dream that you hold in your hand. — Neil Gaiman',
  'if you only read what everyone else reads, you can only think what everyone else thinks. — Haruki Murakami',
  'reading gives us someplace to go when we have to stay where we are. — Mason Cooley',
  'books fall open, you fall in. — David T.W. McCord',
  'the only thing you absolutely have to know is the location of the library. — Albert Einstein',
  "it is what you read when you don't have to that determines what you will be when you can't help it. — Oscar Wilde",
  'show me a family of readers, and I will show you the people who move the world. — Napoleon Bonaparte',
  'there are worse crimes than burning books — one of them is not reading them. — Joseph Brodsky',
  'the world was hers for the reading. — Betty Smith',
  'never trust anyone who has not brought a book with them. — Lemony Snicket',
  'we read to know we are not alone. — attributed to C.S. Lewis',

  // Fun original ones
  'your TBR pile is a retirement plan, not a to-do list.',
  'you can never own too many bookmarks.',
  'one more chapter is a completely reasonable life decision.',
  'the book was always better.',
  '"I\'ll just read one page before bed" is the biggest lie you\'ll ever tell yourself.',
  'a bad book club pick still means good snacks and better gossip.',
  'your library card is basically a passport to infinite worlds.',
  'buying a new book while you have five unread ones is called hope.',
  'readers never sleep alone — they have main characters keeping them company.',
  "it's not hoarding if it's books.",
  "the best conversations happen after someone says 'wait, can we talk about that ending?'",
  'you are the main character of your own story — act accordingly.',
  'a good plot twist is basically therapy.',
  "'just a chapter' and '3 AM' go hand in hand.",
  'wine pairs well with almost any genre.',
  'you can fall in love with a fictional character and still show up with dignity.',
  'your book club opinions are always valid, even the unpopular ones.',
  'the sequel is never too far away.',
  "a cliffhanger is the universe's way of testing your patience.",
  'you survived that one book everyone hated — you can survive anything.',
  'rereading your favorite book is basically visiting an old friend.',
  'the smell of a new book is a personality trait.',
  "'I didn't like the ending' is a valid book club contribution.",
  'your annotations are basically a diary in disguise.',
  "you don't need a bookmark if you fold the corner.",
  'judging a book by its cover is half the fun of browsing.',
  'a slow burn is worth the wait — in books and in life.',
  'your reading speed is not a competition (unless it is).',
  'audiobooks count, no exceptions.',
  'you can DNF a book and still hold your head high.',
  'the best plot twists deserve a group chat message immediately.',
  'crying over a book is a sign of excellent writing.',
  "you're allowed to have five books going at once.",
  "your favorite author doesn't know how much they mean to you (yet).",
  'a well-timed book recommendation is one of the greatest gifts.',
  'your book club snacks are just as important as the discussion questions.',
  'rainy days were made for reading marathons.',
  'the villain probably had a point.',
  "your 'quick trip to the bookstore' was never quick.",
  'a plot hole is just an opportunity for debate.',
  'the footnotes are half the fun in a good book.',
  'you can love a book and still roast it a little.',
  'chapter titles are an underrated art form.',
  'your book club is basically a support group with extra steps.',
  'the best endings leave you a little heartbroken.',
  'a coffee shop and a good book are an unbeatable combo.',
  'your opinions on love triangles are always welcome here.',
  "you're never too old for a good plot twist.",
  'the margins are for scribbling your feelings.',
  'a good book club pick sparks at least one fun argument.',
  "three chapters in is when you know if it's a keeper.",
  'you deserve a cozy reading nook, no exceptions.',
  'unread books on your shelf are basically potential energy.',
  'the author owes you nothing, but that ending still hurt.',
  'a good cliffhanger chapter ending is a personal attack.',
  "your book club friends 'get it' more than anyone else.",
  'reading in public makes you look unbothered and mysterious.',
  "you can love the book and still think the movie wasn't that bad.",
  'a good twist villain deserves a spinoff.',
  "you'll never regret staying up too late for 'just one more chapter.'",
  'your annotated copy is a future heirloom.',
  'a satisfying epilogue is worth the whole book.',
  'the best characters ruin you for real people (kidding, mostly).',
  'your bookshelf tells a story of its own.',
  'a great book club discussion is cheaper than therapy.',
  "the 'one more page' rule has no enforceable boundaries.",
  "you don't need permission to reread your comfort book for the tenth time.",
  'a well-worn spine means a well-loved book.',
  'showing up to book club without finishing the book is a rite of passage.',
  'your favorite genre says more about you than your horoscope does.',
  'a good ending makes you want to hug the book.',
  'the plot always thickens when snacks run low.',
  "you're allowed to skip the boring chapters (we won't tell).",
  'your book club is proof that grown-ups still love story time.',
  'every book you finish is a tiny victory worth celebrating.',
]

export function getRandomQuote(): string {
  const index = Math.floor(Math.random() * bookClubQuotes.length)
  return bookClubQuotes[index]
}
