export const CATEGORIES = [
  'Food & Grocery',
  'Gifts & Hampers',
  'Clothing & Fashion',
  'Beauty & Health',
  'Restaurants & Takeaway',
  'Services',
  'Online Stores',
  'Books & Media',
  'Home & Garden',
  'Other',
] as const

export const COUNTRIES = [
  'Australia',
  'Canada',
  'China',
  'Colombia',
  'France',
  'Germany',
  'Greece',
  'Hong Kong',
  'India',
  'Ireland',
  'Israel',
  'Italy',
  'Luxembourg',
  'Mauritius',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Poland',
  'Portugal',
  'Singapore',
  'South Africa',
  'South Korea',
  'Spain',
  'Thailand',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Other',
] as const

export const PRODUCT_TAGS = [
  'Amarula',
  'Beskuit',
  'Biltong',
  'Biltong Spices',
  'Boerewors',
  'Bobotie',
  'Braai',
  'Bunny Chow',
  'Catering',
  'Chakalaka',
  'Chilli Bites',
  'Clothing',
  'Droëwors',
  'Gifts',
  'Groceries',
  'Hot Sauce',
  'Jewellery',
  'Koeksisters',
  'Lamb',
  'Leather Goods',
  'Melktert',
  'Milk Tart',
  'Ostrich',
  'Peri-peri',
  'Potjiekos',
  'Rooibos',
  'Rusks',
  'Spices',
  'Spit Roast',
  'Springbok',
  'Vetkoek',
  'Wine',
] as const

export type Category = (typeof CATEGORIES)[number]
export type Country = (typeof COUNTRIES)[number]
export type ProductTag = (typeof PRODUCT_TAGS)[number]

export const EVENT_CATEGORIES = [
  'Community & Networking',
  'Food & Braai',
  'Music & Entertainment',
  'Sports & Outdoors',
  'Cultural & Heritage',
  'Markets & Shopping',
  'Family & Kids',
  'Business & Professional',
  'Other',
] as const

export type EventCategory = (typeof EVENT_CATEGORIES)[number]

export const SA_COLORS = {
  green: '#007A4D',
  gold: '#FFB612',
  red: '#DE3831',
  blue: '#002395',
  black: '#000000',
  white: '#FFFFFF',
} as const
